export const ACTIONS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
  GET_CART: "GET_CART",
  CHANGE_CART_LENGTH: "CHANGE_CART_LENGTH",
  EDIT_CAR: "EDIT_CAR"
};

export const JSON_API_PRODUCTS = 'http://localhost:8000/products';